In [262]:
import sklearn
import numpy as np

In [264]:
y1 = 1.0
y2 = 2.0
y3 = 3.0
y4 = 4.0
y5 = 5.0
y6 = 6.0

y0 = 1.00

E0 = 10

R = np.zeros((3, 3))
R[0][0] = y0 + y4 + y1 + y6
R[1][1] = y3 + y4 + y5
R[2][2] = y1 + y2 + y3

R[0][1] = -y4
R[1][0] = -y4

R[1][2] = -y3
R[2][1] = -y3

R[0][2] = -y1
R[2][0] = -y1

U = np.zeros((3, 1))
E = np.zeros((3, 1))
E[0, 0] = E0
print(R)

[[ 12.  -4.  -1.]
 [ -4.  12.  -3.]
 [ -1.  -3.   6.]]


In [265]:
from scipy.linalg import solve
U = solve(R, E)
print(U)

[[ 1.00961538]
 [ 0.43269231]
 [ 0.38461538]]


In [266]:
Ut = 2.0
L = (Ut - U[0, 0])**2
L

0.98086168639053262

In [267]:
#градиентный спуск
from sympy import *

#создаём символы для дальнейшей подстановки
ys0, ys1, ys2, ys3, ys4, ys5, ys6 = symbols('ys0 ys1 ys2 ys3 ys4 ys5 ys6')
ys = [ys0, ys1, ys2, ys3, ys4, ys5, ys6]
y = [y0, y1, y2, y3, y4, y5, y6]


#задаём функцию, которую собираемся минимизировать, с символами

#минор R[0,0]
detR00 = 10.0 * (ys[3]+ys[4]+ys[5]) * (ys[1]+ys[2]+ys[3]) - (-ys[1]) * (-ys[1])

#определитель матрицы еврейским методом
main_diag = (ys[0]+ys[1]+ys[4]+ys[6]) * (ys[3]+ys[4]+ys[5]) * (ys[1]+ys[2]+ys[3])
main_tri1 = (-ys[1]) * (-ys[3]) * (-ys[4])
main_tri2 = (-ys[1]) * (-ys[3]) * (-ys[4])

anti_diag = (ys[3]+ys[4]+ys[5]) * (-ys[3]) * (-ys[3])
anti_tri1 = (ys[1]+ys[2]+ys[3]) * (-ys[4]) * (-ys[4])
anti_tri2 = (ys[0]+ys[1]+ys[4]+ys[6]) * (-ys[1]) * (-ys[1])

detR = (main_diag + main_tri1 + main_tri2) - (anti_diag + anti_tri1 + anti_tri2)

#и считаем методом крамера
Ug = detR00 / detR

#is this loss
loss = (2.0 - Ug)**2

In [269]:
#копируем матрицу с сопротивлениями _на_всякий_случай_
R1 = R.copy()
print(R1)

[[ 12.  -4.  -1.]
 [ -4.  12.  -3.]
 [ -1.  -3.   6.]]


In [270]:
#задаём гиперпараметры: минимальную ошибку и максимальное число итераций
EPS = 0.01
MAX_ITERATION = 5000000
lam = 0.01

In [271]:
#иии градиентный спуск
grad=np.zeros((8, 1))
R = R1.copy()
g0, g1, g2, g3, g4, g5, g6 = symbols('g0 g1 g2 g3 g4 g5 g6')
sym_grad = [g0, g1, g2, g3, g4, g5, g6]
i = 0
print(R)

while L > EPS and i < MAX_ITERATION:  
    for j in range(len(ys)):
        #считаем просто частные производные
        sym_grad[j] = loss.diff(ys[j])
        
        #считаем значения частных производных в точке aka градиент
        grad[j] = float(sym_grad[j].subs([(ys[0], y[0]), (ys[1], y[1]), (ys[2], y[2]), (ys[3], y[3]), (ys[4], y[4]), (ys[5], y[5]), (ys[6], y[6])]))
    
    #обновляем только когда посчитали всё!!!
    for j in range(len(ys)):
        y[j] = y[j] - lam * grad[j]
    
    #мы УЖЕ минимизируем функцию потерь, заново ничего возводить в степень не надо, просто подставить
    L = loss.subs([(ys[0], y[0]), (ys[1], y[1]), (ys[2], y[2]), (ys[3], y[3]), (ys[4], y[4]), (ys[5], y[5]), (ys[6], y[6])])
    
    #выводим лосс каждые 10 шагов
    if i%10 == 0:
        print(L)
    
    i += 1
    

    

[[ 12.  -4.  -1.]
 [ -4.  12.  -3.]
 [ -1.  -3.   6.]]
0.717126265970382
0.701342471115124
0.685308365787732
0.669023060808194
0.652486369266473
0.635698916213598
0.618662261142535
0.601379034279036
0.583853087651720
0.566089661806301
0.548095568853467
0.529879392272365
0.511451703506302
0.492825294854012
0.474015427444221
0.455040092144755
0.435920280059351
0.416680257765080
0.397347840604913
0.377954655148652
0.358536379366892
0.339132946156136
0.319788692687400
0.300552434774429
0.281477442311059
0.262621289164027
0.244045549210638
0.225815310096200
0.207998478484107
0.190664855871155
0.173884973189685
0.157728685965144
0.142263549883636
0.127553018740257
0.113654531499618
0.100617580199643
0.0884818722815429
0.0772757155662984
0.0670147573922244
0.0577011980755762
0.0493235713804424
0.0418571422802681
0.0352649191919016
0.0294992209608813
0.0245036865734870
0.0202155760299252
0.0165681901084949
0.0134932374682853
0.0109229982681422


In [272]:
    R[0][0] = y[0] + y[4] + y[1] + y[6]
    R[1][1] = y[3] + y[4] + y[5]
    R[2][2] = y[1] + y[2] + y[3]

    R[0][1] = -y[4]
    R[1][0] = -y[4]

    R[1][2] = -y[3]
    R[2][1] = -y[3]

    R[0][2] = -y[1]
    R[2][0] = -y[1]
    
    
    print(R)

[[  8.86817342  -3.58719498  -0.19439865]
 [ -3.58719498  12.15667865  -3.68815315]
 [ -0.19439865  -3.68815315   5.51214439]]


In [273]:
for k in range(len(y)):
    print('y', k, y[k])

y 0 [ 0.04328989]
y 1 [ 0.19439865]
y 2 [ 1.62959259]
y 3 [ 3.68815315]
y 4 [ 3.58719498]
y 5 [ 4.88133051]
y 6 [ 5.04328989]
