In [20]:
import random
import sklearn
import numpy as np

In [21]:
y = []
for k in range(7):
    y.append(random.uniform(0, 1))

E0 = 10

U = np.zeros((3, 1))
E = np.zeros((3, 1))
E[0, 0] = E0
print(y)

[0.6550726246679168, 0.4885036354267003, 0.9775105833462302, 0.5615620937457312, 0.35869262820530246, 0.09329131893947662, 0.00501522306019031]


In [22]:
def my_func(ys):
#задаём функцию, которую собираемся минимизировать
#минор R[0,0]
    detR00 = 10.0 * (ys[3]+ys[4]+ys[5]) * (ys[1]+ys[2]+ys[3]) - (-ys[1]) * (-ys[1])

#определитель матрицы еврейским методом
    main_diag = (ys[0]+ys[1]+ys[4]+ys[6]) * (ys[3]+ys[4]+ys[5]) * (ys[1]+ys[2]+ys[3])
    main_tri1 = (-ys[1]) * (-ys[3]) * (-ys[4])
    main_tri2 = (-ys[1]) * (-ys[3]) * (-ys[4])

    anti_diag = (ys[3]+ys[4]+ys[5]) * (-ys[3]) * (-ys[3])
    anti_tri1 = (ys[1]+ys[2]+ys[3]) * (-ys[4]) * (-ys[4])
    anti_tri2 = (ys[0]+ys[1]+ys[4]+ys[6]) * (-ys[1]) * (-ys[1])

    detR = (main_diag + main_tri1 + main_tri2) - (anti_diag + anti_tri1 + anti_tri2)

#и считаем методом крамера
    Ug = detR00 / detR

#is this loss
    loss = (2.0 - Ug)**2
    
    return loss

In [23]:
#задаём гиперпараметры: минимальную ошибку и максимальное число итераций
EPS = 0.001
MAX_ITERATION = 500000
lam = 0.1
step = 0.5

In [24]:
j = 0
print(R)
y_new = y.copy()
print(my_func(y))
while step > EPS and j < MAX_ITERATION:  
    basic = my_func(y)
    for i in range(len(y)):
        y_new[i] += step
        if basic <= my_func(y_new):
            step /= 2.0
            i = -1
            break
    if i != -1:
        y = y_new.copy()
    print('Loss = ', my_func(y))
    print('Step = ', step)
    j += 1

        
        

[[ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]
69.89367278926767
Loss =  5.249233673733541
Step =  0.5
Loss =  0.5093344302879829
Step =  0.5
Loss =  0.00021245284134354943
Step =  0.5
Loss =  0.00021245284134354943
Step =  0.25
Loss =  0.00021245284134354943
Step =  0.125
Loss =  0.00021245284134354943
Step =  0.0625
Loss =  0.00021245284134354943
Step =  0.03125
Loss =  0.00021245284134354943
Step =  0.015625
Loss =  0.00021245284134354943
Step =  0.0078125
Loss =  0.00021245284134354943
Step =  0.00390625
Loss =  0.00021245284134354943
Step =  0.001953125
Loss =  0.00021245284134354943
Step =  0.0009765625


In [25]:
for k in range(len(y)):
    print('y', k, y[k])

y 0 2.155072624667917
y 1 1.9885036354267003
y 2 2.47751058334623
y 3 2.061562093745731
y 4 1.8586926282053025
y 5 1.5932913189394766
y 6 1.5050152230601903
